In [306]:
import os               #importo os para conocer mi ubicación
import csv              #importo csv por el tipo de archivo a trabajar
import pandas as pd     #importo pandas para manejar los dataframes

In [307]:
os.listdir()            #Reviso que los archivos estén en mi ubicación de trabajo

['credits.csv',
 'datasets',
 'ETL + EDA backup.ipynb',
 'ETL + EDA.ipynb',
 'FuncionScore.csv',
 'FuncionVotos.csv',
 'images',
 'main.py',
 'movies_dataset.csv',
 'PeliculasPorDiaListo.csv',
 'Procfile',
 'README.md',
 'requirements.txt',
 '__pycache__']

In [308]:
Credits = pd.read_csv("credits.csv")                #cargo los archivos en variables diferentes
Movies = pd.read_csv("movies_dataset.csv") 

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\875673591.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  Movies = pd.read_csv("movies_dataset.csv")


In [309]:
Credits.head()                              #Reviso los datos de manera visual

cast  \
0  [{'cast_id': 14, 'character': 'Woody (voice)',...   
1  [{'cast_id': 1, 'character': 'Alan Parrish', '...   
2  [{'cast_id': 2, 'character': 'Max Goldman', 'c...   
3  [{'cast_id': 1, 'character': "Savannah 'Vannah...   
4  [{'cast_id': 1, 'character': 'George Banks', '...   

                                                crew     id  
0  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...    862  
1  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...   8844  
2  [{'credit_id': '52fe466a9251416c75077a89', 'de...  15602  
3  [{'credit_id': '52fe44779251416c91011acb', 'de...  31357  
4  [{'credit_id': '52fe44959251416c75039ed7', 'de...  11862

In [310]:
Credits.info()                  #Reviso la composición de los datos, estructura y tipo de datos. --> Estan full las filas de datos.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 1.0+ MB


In [311]:
Movies.head()               #Reviso los datos de manera visual

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2  A family wedding reignites the ancient feud be...  ...   1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4  Just when George Banks has recovered from his ...  ...   1995-02-10   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7     5415.0  
1                      Jumanji  False          6.9     2413.0  
2             Grumpier Old Men  False          6.5       92.0  
3            Waiting to Exhale  False          6.1       34.0  
4  Father of the Bride Part II  False          5.7      173.0  

[5 rows x 24 columns]

In [312]:
Movies.info()                           #Reviso la composición de los datos, estructura y tipo de datos. --->>> Hay faltantes en varias columnas.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

Eliminar duplicados

In [313]:
Movies.drop_duplicates(inplace=True)
Credits.drop_duplicates(inplace=True)

Voy a trabajar Movies porque hay faltantes

In [314]:
#Primero necesito saber que columnas están más afectadas, uso el loop para visualizar de a grupos sin que se corte el output

for i in range(0, len(Movies.columns)-19):          #Columnas 0 a 4
    column = Movies.columns[i]
    print(f"Missing values in '{column}':")
    print(Movies[column].isna().value_counts())
    print()  # Mejora la legibilidad

Missing values in 'adult':
adult
False    45453
Name: count, dtype: int64

Missing values in 'belongs_to_collection':
belongs_to_collection
True     40959
False     4494
Name: count, dtype: int64

Missing values in 'budget':
budget
False    45453
Name: count, dtype: int64

Missing values in 'genres':
genres
False    45453
Name: count, dtype: int64

Missing values in 'homepage':
homepage
True     37673
False     7780
Name: count, dtype: int64



In [315]:
for i in range(5, len(Movies.columns)-14):          #Columnas 5 a 9
    column = Movies.columns[i]
    print(f"Missing values in '{column}':")
    print(Movies[column].isna().value_counts())
    print() 

Missing values in 'id':
id
False    45453
Name: count, dtype: int64

Missing values in 'imdb_id':
imdb_id
False    45436
True        17
Name: count, dtype: int64

Missing values in 'original_language':
original_language
False    45442
True        11
Name: count, dtype: int64

Missing values in 'original_title':
original_title
False    45453
Name: count, dtype: int64

Missing values in 'overview':
overview
False    44499
True       954
Name: count, dtype: int64



In [316]:
for i in range(10, len(Movies.columns)-9):          #Columnas 10 a 14
    column = Movies.columns[i]
    print(f"Missing values in '{column}':")
    print(Movies[column].isna().value_counts())
    print() 

Missing values in 'popularity':
popularity
False    45448
True         5
Name: count, dtype: int64

Missing values in 'poster_path':
poster_path
False    45067
True       386
Name: count, dtype: int64

Missing values in 'production_companies':
production_companies
False    45450
True         3
Name: count, dtype: int64

Missing values in 'production_countries':
production_countries
False    45450
True         3
Name: count, dtype: int64

Missing values in 'release_date':
release_date
False    45366
True        87
Name: count, dtype: int64



In [317]:
for i in range(15, len(Movies.columns)-4):          #Columnas 15 a 19
    column = Movies.columns[i]
    print(f"Missing values in '{column}':")
    print(Movies[column].isna().value_counts())
    print() 

Missing values in 'revenue':
revenue
False    45447
True         6
Name: count, dtype: int64

Missing values in 'runtime':
runtime
False    45190
True       263
Name: count, dtype: int64

Missing values in 'spoken_languages':
spoken_languages
False    45447
True         6
Name: count, dtype: int64

Missing values in 'status':
status
False    45366
True        87
Name: count, dtype: int64

Missing values in 'tagline':
tagline
True     25045
False    20408
Name: count, dtype: int64



In [318]:
for i in range(20, len(Movies.columns)):          #Columnas 20 a 23
    column = Movies.columns[i]
    print(f"Missing values in '{column}':")
    print(Movies[column].isna().value_counts())
    print() 

Missing values in 'title':
title
False    45447
True         6
Name: count, dtype: int64

Missing values in 'video':
video
False    45447
True         6
Name: count, dtype: int64

Missing values in 'vote_average':
vote_average
False    45447
True         6
Name: count, dtype: int64

Missing values in 'vote_count':
vote_count
False    45447
True         6
Name: count, dtype: int64



Lo hago así porque me gusta ser exhaustivo con los datos que voy a manejar, es un análisis que lleva más tiempo pero que no deja lugar a dudas.

In [319]:
for column in Movies.columns:
    print(column)

adult
belongs_to_collection
budget
genres
homepage
id
imdb_id
original_language
original_title
overview
popularity
poster_path
production_companies
production_countries
release_date
revenue
runtime
spoken_languages
status
tagline
title
video
vote_average
vote_count


In [320]:
'''Conclusiones:

adult                   --> completo
belongs_to_collection   --> 40972 vacios ||  4494 datos             --------------Atención
budget                  --> completo
genres                  --> completo
homepage                --> 37684 vacios || 7782 datos              --------------Atención
id                      --> completo
imdb_id                 --> faltan 17
original_language       --> faltan 11 
original_title          --> completo
overview                --> faltan 954
popularity              --> faltan 5
poster_path             --> faltan 3
production_companies    --> faltan 3
production_countries    --> faltan 386
release_date            --> faltan 87
revenue                 --> faltan 6
runtime                 --> faltan 263
spoken_languages        --> faltan 6
status                  --> faltan 87
tagline                 --> 25054 vacios || 20412 datos             --------------Atención
title                   --> faltan 6
video                   --> faltan 6
vote_average            --> faltan 6
vote_count              --> faltan 6


3 columnas con faltantes importantes ||| 5 completas ||| 3 con +100 faltantes ||| 13 con -100 faltantes'''

'Conclusiones:\n\nadult                   --> completo\nbelongs_to_collection   --> 40972 vacios ||  4494 datos             --------------Atención\nbudget                  --> completo\ngenres                  --> completo\nhomepage                --> 37684 vacios || 7782 datos              --------------Atención\nid                      --> completo\nimdb_id                 --> faltan 17\noriginal_language       --> faltan 11 \noriginal_title          --> completo\noverview                --> faltan 954\npopularity              --> faltan 5\nposter_path             --> faltan 3\nproduction_companies    --> faltan 3\nproduction_countries    --> faltan 386\nrelease_date            --> faltan 87\nrevenue                 --> faltan 6\nruntime                 --> faltan 263\nspoken_languages        --> faltan 6\nstatus                  --> faltan 87\ntagline                 --> 25054 vacios || 20412 datos             --------------Atención\ntitle                   --> faltan 6\nvideo      

### El enunciado pide que  •	Los valores nulos de los campos revenue, budget deben ser rellenados por el número 0

In [321]:
# Check de valores nulos en ambas columnas
print(Movies["budget"].isna().value_counts())
print(Movies["revenue"].isna().value_counts())

budget
False    45453
Name: count, dtype: int64
revenue
False    45447
True         6
Name: count, dtype: int64


In [322]:
#Rellenamos los 6 faltantes de revenue (budget figura sin nulos)
Movies.revenue.fillna(0, inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\243367641.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Movies.revenue.fillna(0, inplace=True)


### Segundo punto (del dataset Movies) pide   •	Los valores nulos del campo release date deben eliminarse.

In [323]:
# Faltaban 87 valores --> no aclara que tipo de eliminación por lo que eliminaré las filas completas.
Movies.dropna(subset=["release_date"],inplace=True)

In [324]:
Movies.release_date.isna().value_counts()

release_date
False    45366
Name: count, dtype: int64

### Tercer punto   •A) De haber fechas, deberán tener el formato AAAA-mm-dd

In [325]:
Movies.head(1) #Se observa que release_date tiene estructura de fecha. 

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   

                               homepage   id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story  862  tt0114709                en   

  original_title                                           overview  ...  \
0      Toy Story  Led by Woody, Andy's toys live happily in his ...  ...   

  release_date      revenue runtime                          spoken_languages  \
0   1995-10-30  373554033.0    81.0  [{'iso_639_1': 'en', 'name': 'English'}]   

     status  tagline      title  video vote_average vote_count  
0  Released      NaN  Toy Story  False          7.7     5415.0  

[1 rows x 24 columns]

In [326]:
Movies.info() #Se observa que release_date es tipo object

<class 'pandas.core.frame.DataFrame'>
Index: 45366 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45366 non-null  object 
 1   belongs_to_collection  4491 non-null   object 
 2   budget                 45366 non-null  object 
 3   genres                 45366 non-null  object 
 4   homepage               7767 non-null   object 
 5   id                     45366 non-null  object 
 6   imdb_id                45352 non-null  object 
 7   original_language      45355 non-null  object 
 8   original_title         45366 non-null  object 
 9   overview               44425 non-null  object 
 10  popularity             45364 non-null  object 
 11  poster_path            45027 non-null  object 
 12  production_companies   45366 non-null  object 
 13  production_countries   45366 non-null  object 
 14  release_date           45366 non-null  object 
 15  revenue

In [327]:
#Cambiar tipo de dato de release_date a fecha (aaaa-mm-dd)

Movies["release_date"] = pd.to_datetime(Movies["release_date"], errors="coerce")
print(Movies["release_date"].dtype) #Comprobar tipo de dato

datetime64[ns]


### Continuación tercer punto B) además deberán crear la columna release_year 

In [328]:
print(Movies["release_date"].dtype)

datetime64[ns]


In [329]:
import datetime as dt       # importar libreria de tiempo
Movies["release_year"] = Movies["release_date"].dt.year.astype("Int64")  #Investigando, pandas por defecto extrae tipo float

In [330]:
print(Movies["release_year"])
print(Movies["release_year"].dtype)  #Comprobamos

0        1995
1        1995
2        1995
3        1995
4        1995
         ... 
45460    1991
45462    2011
45463    2003
45464    1917
45465    2017
Name: release_year, Length: 45366, dtype: Int64
Int64


In [331]:
print(Movies["release_year"].value_counts())

release_year
2014    1974
2015    1904
2013    1888
2012    1722
2011    1667
        ... 
2020       1
1887       1
1878       1
1874       1
1883       1
Name: count, Length: 135, dtype: Int64


### Cuarto punto •	Crear la columna con el retorno de inversión, llamada return con los campos revenue y budget

cuando no hay datos disponibles para calcularlo, deberá tomar el valor 0.

In [332]:
#Ante errores de ejecución, hay que verificar tipo de datos
print(Movies["revenue"].dtype)
print(Movies["budget"].dtype)  # ---->>>>tipo object

float64
object


In [333]:
Movies.revenue.isna().value_counts()  #No hay faltantes || Tipo integer

revenue
False    45366
Name: count, dtype: int64

In [334]:
Ganancias = Movies.revenue
Ganancias2 = Ganancias + 10
(Ganancias2 - Ganancias).value_counts()        # Solo hay valores numéricos en revenue

revenue
10.0    45366
Name: count, dtype: int64

In [335]:
Presupuesto = Movies.budget

In [336]:
#Presupuesto2 = Presupuesto + 10     ##Error , detecta string.

In [337]:
for i in Movies["budget"]:          # Check de valores por longitud de caracteres, 10 digitos implicaría un billón de presupuesto (mil millones)
    if len(i) > 10:
        print(i)                 # La salida es correcta

/ff9qCepilowshEtG2GYWwzt2bs4.jpg
/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg
/zaSf5OG7V8X8gqFvly88zDdRm46.jpg


In [338]:
for index, i in enumerate(Movies["budget"]):          # Encontrar el index para eliminar
    if len(i) > 10:
        print(Presupuesto[index])               #La salida es inconsistente

0
0
0


In [339]:
Movies["budget"][0]              # Corroborar valor con el indice arrojado, no coincide.

'30000000'

In [340]:
# Recurrir a eliminar uno por uno con su respectiva salida

Movies["budget"] = Movies["budget"][Movies["budget"] != "/ff9qCepilowshEtG2GYWwzt2bs4.jpg"]
Movies["budget"] = Movies["budget"][Movies["budget"] != "/zaSf5OG7V8X8gqFvly88zDdRm46.jpg"]
Movies["budget"] = Movies["budget"][Movies["budget"] != "/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg"]


In [341]:
Movies["budget"].isna().value_counts()

budget
False    45363
True         3
Name: count, dtype: int64

In [342]:
Movies["budget"].fillna(0,inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1565188767.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Movies["budget"].fillna(0,inplace=True)


In [343]:
Movies["budget"] = Movies["budget"].astype(int)

In [344]:
Movies["revenue"]

0        373554033.0
1        262797249.0
2                0.0
3         81452156.0
4         76578911.0
            ...     
45460            0.0
45462            0.0
45463            0.0
45464            0.0
45465            0.0
Name: revenue, Length: 45366, dtype: float64

In [345]:
# Calcular columna según enunciado, en caso de que el denominador sea cero, reemplazar por NA

Movies["return"] = Movies["revenue"] / Movies["budget"].replace(0,None)

In [346]:
Movies['return']

0        12.451801
1         4.043035
2              NaN
3          5.09076
4              NaN
           ...    
45460          NaN
45462          NaN
45463          NaN
45464          NaN
45465          NaN
Name: return, Length: 45366, dtype: object

In [347]:
Movies["return"].isna().value_counts()

return
True     36481
False     8885
Name: count, dtype: int64

In [348]:
Movies['return'].fillna(0,inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3296156735.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Movies['return'].fillna(0,inplace=True)


In [349]:
Movies['return'].isna().value_counts()

return
False    45366
Name: count, dtype: int64

### Ultimo Punto Movies •	Eliminar las columnas que no serán utilizadas, video,imdb_id,adult,original_title,poster_path y homepage.

In [350]:
Movies = Movies.drop(columns=["video", "imdb_id", "adult", "original_title", "poster_path", "homepage"])

In [351]:
Movies.columns

Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',
       'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'release_year', 'return'],
      dtype='object')

In [352]:
Movies.info()  #Eran 24. Ahora son 20, se crearon release_year + return y se eliminaron 6

<class 'pandas.core.frame.DataFrame'>
Index: 45366 entries, 0 to 45465
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   belongs_to_collection  4491 non-null   object        
 1   budget                 45366 non-null  int32         
 2   genres                 45366 non-null  object        
 3   id                     45366 non-null  object        
 4   original_language      45355 non-null  object        
 5   overview               44425 non-null  object        
 6   popularity             45364 non-null  object        
 7   production_companies   45366 non-null  object        
 8   production_countries   45366 non-null  object        
 9   release_date           45363 non-null  datetime64[ns]
 10  revenue                45366 non-null  float64       
 11  runtime                45117 non-null  float64       
 12  spoken_languages       45363 non-null  object        
 13  status

### Finalizo Tratamiento de Dataset Movies (Base a la propuesta de trabajo)

Inicio Tratamiento Credits --> Primer punto solicitado , los campos belongs_to_collection, production_companies  + deberán desanidarlos para poder y unirlos al dataset de nuevo 

Desanidar Belongs_to_collection

In [353]:
Movies["belongs_to_collection"]

0        {'id': 10194, 'name': 'Toy Story Collection', ...
1                                                      NaN
2        {'id': 119050, 'name': 'Grumpy Old Men Collect...
3                                                      NaN
4        {'id': 96871, 'name': 'Father of the Bride Col...
                               ...                        
45460                                                  NaN
45462                                                  NaN
45463                                                  NaN
45464                                                  NaN
45465                                                  NaN
Name: belongs_to_collection, Length: 45366, dtype: object

In [354]:
Movies["belongs_to_collection"].drop_duplicates(inplace=True)

In [355]:
Movies["belongs_to_collection"].isnull().value_counts()

belongs_to_collection
True     40875
False     4491
Name: count, dtype: int64

In [356]:
# Ver una salida como ejemplo para entender composición instancias.

Movies["belongs_to_collection"][0]

"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"

In [357]:
Movies["belongs_to_collection"][:10]

0    {'id': 10194, 'name': 'Toy Story Collection', ...
1                                                  NaN
2    {'id': 119050, 'name': 'Grumpy Old Men Collect...
3                                                  NaN
4    {'id': 96871, 'name': 'Father of the Bride Col...
5                                                  NaN
6                                                  NaN
7                                                  NaN
8                                                  NaN
9    {'id': 645, 'name': 'James Bond Collection', '...
Name: belongs_to_collection, dtype: object

In [358]:
import pandas as pd
import ast

def desanidar_belongs_to_collection(movies_df):
    # Extraer y desanidar la columna 'belongs_to_collection'
    collection_data = movies_df['belongs_to_collection'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else None)
    
    # Convertir la lista de diccionarios en un DataFrame
    collection_df = pd.json_normalize(collection_data)
    
    return collection_df

belong_to_collection_desanidado = desanidar_belongs_to_collection(Movies)

print(belong_to_collection_desanidado)

             id                            name  \
0       10194.0            Toy Story Collection   
1           NaN                             NaN   
2      119050.0       Grumpy Old Men Collection   
3           NaN                             NaN   
4       96871.0  Father of the Bride Collection   
...         ...                             ...   
45361       NaN                             NaN   
45362       NaN                             NaN   
45363       NaN                             NaN   
45364       NaN                             NaN   
45365       NaN                             NaN   

                            poster_path                     backdrop_path  
0      /7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg  /9FBwqcd9IRruEDUrTdcaafOMKUq.jpg  
1                                   NaN                               NaN  
2      /nLvUdqgPgm3F85NMCii9gVFUcet.jpg  /hypTnLot2z8wpFS7qwsQHW1uV8u.jpg  
3                                   NaN                               NaN  
4      

In [359]:
belong_to_collection = belong_to_collection_desanidado

In [360]:
belong_to_collection  #belong_to_colecction desanidada, falta trabajo de limpieza

id                            name  \
0       10194.0            Toy Story Collection   
1           NaN                             NaN   
2      119050.0       Grumpy Old Men Collection   
3           NaN                             NaN   
4       96871.0  Father of the Bride Collection   
...         ...                             ...   
45361       NaN                             NaN   
45362       NaN                             NaN   
45363       NaN                             NaN   
45364       NaN                             NaN   
45365       NaN                             NaN   

                            poster_path                     backdrop_path  
0      /7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg  /9FBwqcd9IRruEDUrTdcaafOMKUq.jpg  
1                                   NaN                               NaN  
2      /nLvUdqgPgm3F85NMCii9gVFUcet.jpg  /hypTnLot2z8wpFS7qwsQHW1uV8u.jpg  
3                                   NaN                               NaN  
4      /nts4iOmNnq7GNicycMJ9pSAn204.jpg  /7qwE57OVZmMJChBpLEbJEmzUydk.jpg  
...                                 ...                               ...  
45361                               NaN                               NaN  
45362                               NaN                               NaN  
45363                               NaN                               NaN  
45364                               NaN                               NaN  
45365                               NaN                               NaN  

[45366 rows x 4 columns]

Desanidar Production_Companies

In [361]:
Movies["production_companies"]

0           [{'name': 'Pixar Animation Studios', 'id': 3}]
1        [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2        [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3        [{'name': 'Twentieth Century Fox Film Corporat...
4        [{'name': 'Sandollar Productions', 'id': 5842}...
                               ...                        
45460    [{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...
45462               [{'name': 'Sine Olivia', 'id': 19653}]
45463    [{'name': 'American World Pictures', 'id': 6165}]
45464                 [{'name': 'Yermoliev', 'id': 88753}]
45465                                                   []
Name: production_companies, Length: 45366, dtype: object

In [362]:
Movies["production_companies"][0]

"[{'name': 'Pixar Animation Studios', 'id': 3}]"

In [363]:
#Elimina los diccionarios dentro de la columna y retorna listas que incluyen nombre e id de la compania productora
import ast

def extract_production_companies(row):
    # Manejar el caso cuando row es un booleano
    if isinstance(row, bool):
        return []  # Retorna una lista vacía si es un booleano
    
    try:
        companies = ast.literal_eval(row)
        
        # Verifica si companies es una lista
        if not isinstance(companies, list):
            return []  # Retorna una lista vacía si no es una lista
        
        # Crea una lista de tuplas con el nombre y el id de cada compañía
        return [(comp['name'], comp['id']) for comp in companies if isinstance(comp, dict) and 'name' in comp and 'id' in comp]
    
    except (ValueError, SyntaxError) as e:
        return []  # Retorna una lista vacía en caso de error

# Aplica la función a la columna production_companies
production_data = Movies["production_companies"].apply(lambda x: extract_production_companies(x))


In [364]:
production_data      #Se obtienen filas con tuplas, donde cada tupla contiene compania productora y su id.

0                           [(Pixar Animation Studios, 3)]
1        [(TriStar Pictures, 559), (Teitler Film, 2550)...
2          [(Warner Bros., 6194), (Lancaster Gate, 19464)]
3          [(Twentieth Century Fox Film Corporation, 306)]
4        [(Sandollar Productions, 5842), (Touchstone Pi...
                               ...                        
45460    [(Westdeutscher Rundfunk (WDR), 7025), (Workin...
45462                               [(Sine Olivia, 19653)]
45463                    [(American World Pictures, 6165)]
45464                                 [(Yermoliev, 88753)]
45465                                                   []
Name: production_companies, Length: 45366, dtype: object

In [365]:
production_data_desanidada = production_data.explode()

In [366]:
production_data_desanidada    #Se obtienen todas las companias productoras, y el índice sirve de referencia para luego agrupar

0                  (Pixar Animation Studios, 3)
1                       (TriStar Pictures, 559)
1                          (Teitler Film, 2550)
1            (Interscope Communications, 10201)
2                          (Warner Bros., 6194)
                          ...                  
45460    (CanWest Global Communications, 38978)
45462                      (Sine Olivia, 19653)
45463           (American World Pictures, 6165)
45464                        (Yermoliev, 88753)
45465                                       NaN
Name: production_companies, Length: 82287, dtype: object

In [367]:
production_data_desanidada = production_data_desanidada.to_frame()

In [368]:
import pandas as pd
import numpy as np

def desanidar_production_data(data):
    # Crear listas para almacenar los valores
    indices = []
    production_companies = []
    ids = []
    
    # Iterar sobre cada elemento en el dataset
    for index, row in data.iterrows():
        # Si el valor es NaN, simplemente añade un NaN a las listas
        if pd.isna(row[0]):
            indices.append(index)
            production_companies.append(np.nan)
            ids.append(np.nan)
        else:
            # Desanidar el valor que es una tupla
            production_company, id_value = row[0]
            indices.append(index)
            production_companies.append(production_company)
            ids.append(id_value)

    # Crear un nuevo DataFrame con las listas
    production_companies_desanidado = pd.DataFrame({
        'indice': indices,
        'production_company': production_companies,
        'id': ids
    })

    return production_companies_desanidado

production_companies_desanidado = desanidar_production_data(production_data_desanidada)
print(production_companies_desanidado)


C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3844873505.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(row[0]):
C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3844873505.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  production_company, id_value = row[0]


       indice             production_company       id
0           0        Pixar Animation Studios      3.0
1           1               TriStar Pictures    559.0
2           1                   Teitler Film   2550.0
3           1      Interscope Communications  10201.0
4           2                   Warner Bros.   6194.0
...       ...                            ...      ...
82282   45460  CanWest Global Communications  38978.0
82283   45462                    Sine Olivia  19653.0
82284   45463        American World Pictures   6165.0
82285   45464                      Yermoliev  88753.0
82286   45465                            NaN      NaN

[82287 rows x 3 columns]


In [369]:
# Gracias a la función, pudimos desanidar las tuplas y hacer que cada fila contenga su compania productora y agregar una columna con su id. Esto permite consistencia.

production_companies_desanidado #Pendiente de limpieza 

indice             production_company       id
0           0        Pixar Animation Studios      3.0
1           1               TriStar Pictures    559.0
2           1                   Teitler Film   2550.0
3           1      Interscope Communications  10201.0
4           2                   Warner Bros.   6194.0
...       ...                            ...      ...
82282   45460  CanWest Global Communications  38978.0
82283   45462                    Sine Olivia  19653.0
82284   45463        American World Pictures   6165.0
82285   45464                      Yermoliev  88753.0
82286   45465                            NaN      NaN

[82287 rows x 3 columns]

In [370]:
# Una demostración con un id aleatorio de que se corresponde con una y solo una compania.

valor_a_filtrar = 'TriStar Pictures'  #Check tengan mismo ID por compañia
filtro = production_companies_desanidado[production_companies_desanidado['production_company'] == valor_a_filtrar]
print(filtro)

       indice production_company     id
1           1   TriStar Pictures  559.0
226        90   TriStar Pictures  559.0
299       116   TriStar Pictures  559.0
302       118   TriStar Pictures  559.0
385       161   TriStar Pictures  559.0
...       ...                ...    ...
77153   42175   TriStar Pictures  559.0
78493   42976   TriStar Pictures  559.0
78552   43012   TriStar Pictures  559.0
79537   43644   TriStar Pictures  559.0
79829   43832   TriStar Pictures  559.0

[197 rows x 3 columns]


In [371]:
production_companies_desanidado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82287 entries, 0 to 82286
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   indice              82287 non-null  int64  
 1   production_company  70491 non-null  object 
 2   id                  70491 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ MB


In [372]:
production_companies_desanidado.id.value_counts()

id
6194.0     1250
8411.0     1075
4.0        1003
306.0       836
33.0        830
           ... 
47033.0       1
89772.0       1
37361.0       1
37362.0       1
88753.0       1
Name: count, Length: 23688, dtype: int64

In [373]:
production_companies_desanidado.id.isna().value_counts()

id
False    70491
True     11796
Name: count, dtype: int64

In [374]:
production_companies_desanidado.id.fillna(0, inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3209167122.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  production_companies_desanidado.id.fillna(0, inplace=True)


In [375]:
production_companies_desanidado.id.isna().value_counts()

id
False    82287
Name: count, dtype: int64

In [376]:
production_companies_desanidado['id'] = production_companies_desanidado.id.astype(int)

In [377]:
production_companies_desanidado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82287 entries, 0 to 82286
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   indice              82287 non-null  int64 
 1   production_company  70491 non-null  object
 2   id                  82287 non-null  int32 
dtypes: int32(1), int64(1), object(1)
memory usage: 1.6+ MB


In [378]:
production_companies_desanidado["indice"].value_counts()        # Ordena las películas (por el índice) que más companias productoras tuvieron involucradas.

indice
36122    26
22235    26
3786     26
13782    25
13748    24
         ..
20348     1
20347     1
20346     1
20345     1
45465     1
Name: count, Length: 45366, dtype: int64

In [379]:
filtroindice = production_companies_desanidado[production_companies_desanidado['indice'] == 22235]

In [380]:
filtroindice            # Muestra la cantidad de companias productoras que tuvo una película en particular.

indice                production_company     id
44671   22235           Zentropa Entertainments     76
44672   22235                           Coop 99    122
44673   22235             Corazón International    200
44674   22235                        Sputnik Oy    706
44675   22235             Kasander Film Company   1049
44676   22235          MMG Film & TV Production   2075
44677   22235                Column Productions   2412
44678   22235                           Negativ   4595
44679   22235                    Filmes do Tejo  16450
44680   22235                   Fantastic Films  18078
44681   22235           Rattlesnake Productions  25188
44682   22235                       Bianca Film  27559
44683   22235                  Maestranza Films  36920
44684   22235                     E-motion Film  48427
44685   22235                   Athena Film A/S  51549
44686   22235                     Princes Films  51980
44687   22235                     TT Filmműhely  55461
44688   22235                   Cumulus Projekt  55583
44689   22235       Drunken Angel Entertainment  55584
44690   22235          Goran Production Company  55585
44691   22235                    Hargla Company  55586
44692   22235                  Inkas Production  55587
44693   22235              Lychnari Productions  55588
44694   22235  Public Institution Kinemos Grupe  55589
44695   22235                             SHOTS  55590
44696   22235                    Titanic s.r.o.  55591

In [381]:
# Group by para agrupar por índice.
production_companies_conjunto = production_companies_desanidado.groupby('indice')['production_company'].agg(lambda x: ' and '.join(x.dropna())).reset_index()

print(production_companies_conjunto)

       indice                                 production_company
0           0                            Pixar Animation Studios
1           1  TriStar Pictures and Teitler Film and Intersco...
2           2                    Warner Bros. and Lancaster Gate
3           3             Twentieth Century Fox Film Corporation
4           4      Sandollar Productions and Touchstone Pictures
...       ...                                                ...
45361   45460  Westdeutscher Rundfunk (WDR) and Working Title...
45362   45462                                        Sine Olivia
45363   45463                            American World Pictures
45364   45464                                          Yermoliev
45365   45465                                                   

[45366 rows x 2 columns]


Aquí se obtiene las production company por película y dejo un dataset donde puedo obtener la cantidad de peliculas que grabó cada compañia, en caso de ser necesario ese dato más adelante

In [382]:
Movies.head(1)  #Podria intercambiar el production_companies original anidado, por el nuevo valor obtenido

belongs_to_collection    budget  \
0  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   

                                              genres   id original_language  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  862                en   

                                            overview popularity  \
0  Led by Woody, Andy's toys live happily in his ...  21.946943   

                             production_companies  \
0  [{'name': 'Pixar Animation Studios', 'id': 3}]   

                                production_countries release_date  \
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30   

       revenue  runtime                          spoken_languages    status  \
0  373554033.0     81.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

  tagline      title  vote_average  vote_count  release_year     return  
0     NaN  Toy Story           7.7      5415.0          1995  12.451801

In [383]:
# Al tener los mismos índices, reemplazo columnas.

Movies["production_companies"] = production_companies_conjunto["production_company"]

In [384]:
Movies.head(1) #Ahora production_companies se ve mucho más limpio

belongs_to_collection    budget  \
0  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   

                                              genres   id original_language  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  862                en   

                                            overview popularity  \
0  Led by Woody, Andy's toys live happily in his ...  21.946943   

      production_companies                               production_countries  \
0  Pixar Animation Studios  [{'iso_3166_1': 'US', 'name': 'United States o...   

  release_date      revenue  runtime  \
0   1995-10-30  373554033.0     81.0   

                           spoken_languages    status tagline      title  \
0  [{'iso_639_1': 'en', 'name': 'English'}]  Released     NaN  Toy Story   

   vote_average  vote_count  release_year     return  
0           7.7      5415.0          1995  12.451801

In [385]:
#Intentaré el mismo procedimiento con belong_to_collection

belong_to_collection #Solo interesa name, en principio

id                            name  \
0       10194.0            Toy Story Collection   
1           NaN                             NaN   
2      119050.0       Grumpy Old Men Collection   
3           NaN                             NaN   
4       96871.0  Father of the Bride Collection   
...         ...                             ...   
45361       NaN                             NaN   
45362       NaN                             NaN   
45363       NaN                             NaN   
45364       NaN                             NaN   
45365       NaN                             NaN   

                            poster_path                     backdrop_path  
0      /7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg  /9FBwqcd9IRruEDUrTdcaafOMKUq.jpg  
1                                   NaN                               NaN  
2      /nLvUdqgPgm3F85NMCii9gVFUcet.jpg  /hypTnLot2z8wpFS7qwsQHW1uV8u.jpg  
3                                   NaN                               NaN  
4      /nts4iOmNnq7GNicycMJ9pSAn204.jpg  /7qwE57OVZmMJChBpLEbJEmzUydk.jpg  
...                                 ...                               ...  
45361                               NaN                               NaN  
45362                               NaN                               NaN  
45363                               NaN                               NaN  
45364                               NaN                               NaN  
45365                               NaN                               NaN  

[45366 rows x 4 columns]

In [386]:
Movies["belongs_to_collection"] = belong_to_collection["name"]

In [387]:
Movies.head() #Ya se ve un dataset que cumple con los requisitos (mínimos) de la propuesta de trabajo

belongs_to_collection    budget  \
0            Toy Story Collection  30000000   
1                             NaN  65000000   
2       Grumpy Old Men Collection         0   
3                             NaN  16000000   
4  Father of the Bride Collection         0   

                                              genres     id original_language  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...    862                en   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   8844                en   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  15602                en   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  31357                en   
4                     [{'id': 35, 'name': 'Comedy'}]  11862                en   

                                            overview popularity  \
0  Led by Woody, Andy's toys live happily in his ...  21.946943   
1  When siblings Judy and Peter discover an encha...  17.015539   
2  A family wedding reignites the ancient feud be...    11.7129   
3  Cheated on, mistreated and stepped on, the wom...   3.859495   
4  Just when George Banks has recovered from his ...   8.387519   

                                production_companies  \
0                            Pixar Animation Studios   
1  TriStar Pictures and Teitler Film and Intersco...   
2                    Warner Bros. and Lancaster Gate   
3             Twentieth Century Fox Film Corporation   
4      Sandollar Productions and Touchstone Pictures   

                                production_countries release_date  \
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30   
1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15   
2  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   
3  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   
4  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-02-10   

       revenue  runtime                                   spoken_languages  \
0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0    127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0    106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  vote_average  vote_count  release_year  \
0                    Toy Story           7.7      5415.0          1995   
1                      Jumanji           6.9      2413.0          1995   
2             Grumpier Old Men           6.5        92.0          1995   
3            Waiting to Exhale           6.1        34.0          1995   
4  Father of the Bride Part II           5.7       173.0          1995   

      return  
0  12.451801  
1   4.043035  
2   0.000000  
3   5.090760  
4   0.000000

Definimos los dataset que están disponibles para luego empezar a segregar a fin de hacer eficientes las consultas solicitadas

# ARCHIVOS PARA FUNCIONES

In [388]:
Movies.head(1)

belongs_to_collection    budget  \
0  Toy Story Collection  30000000   

                                              genres   id original_language  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  862                en   

                                            overview popularity  \
0  Led by Woody, Andy's toys live happily in his ...  21.946943   

      production_companies                               production_countries  \
0  Pixar Animation Studios  [{'iso_3166_1': 'US', 'name': 'United States o...   

  release_date      revenue  runtime  \
0   1995-10-30  373554033.0     81.0   

                           spoken_languages    status tagline      title  \
0  [{'iso_639_1': 'en', 'name': 'English'}]  Released     NaN  Toy Story   

   vote_average  vote_count  release_year     return  
0           7.7      5415.0          1995  12.451801

In [389]:
Credits.head(1) #Pendiente de trabajar para desanidar

cast  \
0  [{'cast_id': 14, 'character': 'Woody (voice)',...   

                                                crew   id  
0  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...  862

In [390]:
# Para la funcion que requiere peliculas estrenadas en cada mes del año y en cada dia de la semana
Peliculas_Estrenada_Por_MesyDia = Movies[["title","release_date"]]

In [391]:
Peliculas_Estrenada_Por_MesyDia #puedo trabajar el dataset para agregar calendario y tener los días de la semana y el mes por separado para hacer eficiente la consulta

title release_date
0                        Toy Story   1995-10-30
1                          Jumanji   1995-12-15
2                 Grumpier Old Men   1995-12-22
3                Waiting to Exhale   1995-12-22
4      Father of the Bride Part II   1995-02-10
...                            ...          ...
45460                   Robin Hood   1991-05-13
45462          Century of Birthing   2011-11-17
45463                     Betrayal   2003-08-01
45464             Satan Triumphant   1917-10-21
45465                     Queerama   2017-06-09

[45366 rows x 2 columns]

In [392]:
# Extraer el día de la semana y el mes
Peliculas_Estrenada_Por_MesyDia['day_of_week'] = Peliculas_Estrenada_Por_MesyDia['release_date'].dt.day_name()  # Nombre del día de la semana
Peliculas_Estrenada_Por_MesyDia['month'] = Peliculas_Estrenada_Por_MesyDia['release_date'].dt.month_name()  # Nombre del mes

# Mostrar el DataFrame con las nuevas columnas
print(Peliculas_Estrenada_Por_MesyDia)

                             title release_date day_of_week     month
0                        Toy Story   1995-10-30      Monday   October
1                          Jumanji   1995-12-15      Friday  December
2                 Grumpier Old Men   1995-12-22      Friday  December
3                Waiting to Exhale   1995-12-22      Friday  December
4      Father of the Bride Part II   1995-02-10      Friday  February
...                            ...          ...         ...       ...
45460                   Robin Hood   1991-05-13      Monday       May
45462          Century of Birthing   2011-11-17    Thursday  November
45463                     Betrayal   2003-08-01      Friday    August
45464             Satan Triumphant   1917-10-21      Sunday   October
45465                     Queerama   2017-06-09      Friday      June

[45366 rows x 4 columns]


C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1388251546.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Peliculas_Estrenada_Por_MesyDia['day_of_week'] = Peliculas_Estrenada_Por_MesyDia['release_date'].dt.day_name()  # Nombre del día de la semana
C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1388251546.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Peliculas_Estrenada_Por_MesyDia['month'] = Peliculas_Estrenada_Por_MesyDia['release_date'].dt.month_name()  # Nombre del mes


In [393]:
PeliculasPorMes = Peliculas_Estrenada_Por_MesyDia.drop(columns="day_of_week")
PeliculasPorDia = Peliculas_Estrenada_Por_MesyDia.drop(columns="month")

In [394]:
PeliculasPorMes

title release_date     month
0                        Toy Story   1995-10-30   October
1                          Jumanji   1995-12-15  December
2                 Grumpier Old Men   1995-12-22  December
3                Waiting to Exhale   1995-12-22  December
4      Father of the Bride Part II   1995-02-10  February
...                            ...          ...       ...
45460                   Robin Hood   1991-05-13       May
45462          Century of Birthing   2011-11-17  November
45463                     Betrayal   2003-08-01    August
45464             Satan Triumphant   1917-10-21   October
45465                     Queerama   2017-06-09      June

[45366 rows x 3 columns]

In [395]:
PeliculasPorMes = PeliculasPorMes.drop(columns="release_date")
PeliculasPorDia = PeliculasPorDia.drop(columns="release_date")

Guardar Archivos función mes

# CSV PeliculasPorMes

In [396]:
PeliculasPorMes.to_csv("datasets\\PeliculasPorMesListo.csv",index=False)

Guardar Archivos función día

# CSV PeliculasPorDia

In [397]:
PeliculasPorDia.to_csv("datasets\\PeliculasPorDiaListo.csv",index=False)

Descubrí que esto era hardcodear y no quedó definido en la función, solo a modo de establecer los valores.

In [398]:
##Aqui podría pensar en ya procesar el dataset para hacer el calculo y solo tenga que hacer una simple consulta el render
TotalPeliculasMes = PeliculasPorMes.groupby('month').size().reset_index(name='total_movies')

In [399]:
TotalPeliculasMes

month  total_movies
0       April          3453
1      August          3394
2    December          3784
3    February          3029
4     January          5910
5        July          2640
6        June          3152
7       March          3553
8         May          3338
9    November          3661
10    October          4613
11  September          4836

In [400]:
TotalPeliculasDia = PeliculasPorDia.groupby('day_of_week').size().reset_index(name='total_movies')

In [401]:
TotalPeliculasDia

day_of_week  total_movies
0      Friday         13906
1      Monday          3501
2    Saturday          5151
3      Sunday          3612
4    Thursday          7522
5     Tuesday          4640
6   Wednesday          7031

Siguiendo con el desarrollo de datasets para funciones.

In [402]:
FuncionScore = Movies[["title","release_year","popularity"]]

In [403]:
FuncionScore["popularity"].isna().value_counts()

popularity
False    45364
True         2
Name: count, dtype: int64

In [404]:
FuncionScore["popularity"].fillna(0,inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3590323140.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  FuncionScore["popularity"].fillna(0,inplace=True)
C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3590323140.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionScore["popularity"].fillna(0,inplace=True)


In [405]:
FuncionScore.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45366 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   title         45363 non-null  object
 1   release_year  45363 non-null  Int64 
 2   popularity    45366 non-null  object
dtypes: Int64(1), object(2)
memory usage: 2.4+ MB


In [406]:
FuncionScore['popularity_numeric'] = pd.to_numeric(FuncionScore['popularity'], errors='coerce')

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3241547926.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionScore['popularity_numeric'] = pd.to_numeric(FuncionScore['popularity'], errors='coerce')


In [407]:
FuncionScore["popularity_numeric"].fillna(0)

0        21.946943
1        17.015539
2        11.712900
3         3.859495
4         8.387519
           ...    
45460     5.683753
45462     0.178241
45463     0.903007
45464     0.003503
45465     0.163015
Name: popularity_numeric, Length: 45366, dtype: float64

In [408]:
FuncionScore.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45366 entries, 0 to 45465
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               45363 non-null  object 
 1   release_year        45363 non-null  Int64  
 2   popularity          45366 non-null  object 
 3   popularity_numeric  45365 non-null  float64
dtypes: Int64(1), float64(1), object(2)
memory usage: 2.8+ MB


In [409]:
FuncionScore["popularity_numeric"] = round(FuncionScore["popularity_numeric"],2)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1786479633.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionScore["popularity_numeric"] = round(FuncionScore["popularity_numeric"],2)


In [410]:
print(FuncionScore["title"].isna().value_counts())
print(FuncionScore["release_year"].isna().value_counts())
print(FuncionScore["popularity_numeric"].isna().value_counts())

title
False    45363
True         3
Name: count, dtype: int64
release_year
False    45363
True         3
Name: count, dtype: int64
popularity_numeric
False    45365
True         1
Name: count, dtype: int64


In [411]:
#Se ingresa el título de una filmación esperando como respuesta el título, el año de estreno y el score.
FuncionScore.dropna(inplace=True)
FuncionScore = FuncionScore.drop(columns=["popularity"])

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1553216218.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionScore.dropna(inplace=True)


Aprovecho para definir el intervalo de años con que cuenta el dataset y darle información al usuario.

In [412]:
print(Movies["release_date"].min())
print(Movies["release_date"].max())

1874-12-09 00:00:00
2020-12-16 00:00:00


# CSV FuncionScore

Guarda de archivos Funcion Score

In [413]:
FuncionScore.to_csv('datasets\\FuncionScore.csv', index=False, header=["title","release_year","popularity"])

Funcion 4 --> Se ingresa el título de una filmación esperando como respuesta el título, la cantidad de votos y el valor promedio de las votaciones.

In [414]:
FuncionVotos = Movies[["title","vote_count","vote_average"]]
FuncionVotos.dropna(inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\603433661.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionVotos.dropna(inplace=True)


In [415]:
FuncionVotos

title  vote_count  vote_average
0                        Toy Story      5415.0           7.7
1                          Jumanji      2413.0           6.9
2                 Grumpier Old Men        92.0           6.5
3                Waiting to Exhale        34.0           6.1
4      Father of the Bride Part II       173.0           5.7
...                            ...         ...           ...
45460                   Robin Hood        26.0           5.7
45462          Century of Birthing         3.0           9.0
45463                     Betrayal         6.0           3.8
45464             Satan Triumphant         0.0           0.0
45465                     Queerama         0.0           0.0

[45363 rows x 3 columns]

In [416]:
FuncionVotos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45363 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         45363 non-null  object 
 1   vote_count    45363 non-null  float64
 2   vote_average  45363 non-null  float64
dtypes: float64(2), object(1)
memory usage: 1.4+ MB


In [417]:
FuncionVotos["vote_count"] = FuncionVotos["vote_count"].astype(int)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1448764649.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionVotos["vote_count"] = FuncionVotos["vote_count"].astype(int)


In [418]:
FuncionVotos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45363 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         45363 non-null  object 
 1   vote_count    45363 non-null  int32  
 2   vote_average  45363 non-null  float64
dtypes: float64(1), int32(1), object(1)
memory usage: 1.2+ MB


In [419]:
FuncionVotos.isna().value_counts()

title  vote_count  vote_average
False  False       False           45363
Name: count, dtype: int64

In [420]:
print(FuncionVotos[FuncionVotos["vote_count"]==0])

                              title  vote_count  vote_average
83      Last Summer in the Hamptons           0           0.0
107    Headless Body in Topless Bar           0           0.0
126                  Jupiter's Wife           0           0.0
132                   Sonic Outlaws           0           0.0
137                          Target           0           0.0
...                             ...         ...           ...
45432                 Altar of Fire           0           0.0
45434        The Wonders of Aladdin           0           0.0
45452                   Deep Hearts           0           0.0
45464              Satan Triumphant           0           0.0
45465                      Queerama           0           0.0

[2848 rows x 3 columns]


Guarda de archivos Funcion Votos

# CSV FuncionVotos

In [421]:
FuncionVotos.to_csv('datasets\\FuncionVotos.csv', index=False, header=["title","vote_count","vote_average"])

In [422]:
Credits

cast  \
0      [{'cast_id': 14, 'character': 'Woody (voice)',...   
1      [{'cast_id': 1, 'character': 'Alan Parrish', '...   
2      [{'cast_id': 2, 'character': 'Max Goldman', 'c...   
3      [{'cast_id': 1, 'character': "Savannah 'Vannah...   
4      [{'cast_id': 1, 'character': 'George Banks', '...   
...                                                  ...   
45471  [{'cast_id': 0, 'character': '', 'credit_id': ...   
45472  [{'cast_id': 1002, 'character': 'Sister Angela...   
45473  [{'cast_id': 6, 'character': 'Emily Shaw', 'cr...   
45474  [{'cast_id': 2, 'character': '', 'credit_id': ...   
45475                                                 []   

                                                    crew      id  
0      [{'credit_id': '52fe4284c3a36847f8024f49', 'de...     862  
1      [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...    8844  
2      [{'credit_id': '52fe466a9251416c75077a89', 'de...   15602  
3      [{'credit_id': '52fe44779251416c91011acb', 'de...   31357  
4      [{'credit_id': '52fe44959251416c75039ed7', 'de...   11862  
...                                                  ...     ...  
45471  [{'credit_id': '5894a97d925141426c00818c', 'de...  439050  
45472  [{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...  111109  
45473  [{'credit_id': '52fe4776c3a368484e0c8387', 'de...   67758  
45474  [{'credit_id': '533bccebc3a36844cf0011a7', 'de...  227506  
45475  [{'credit_id': '593e676c92514105b702e68e', 'de...  461257  

[45439 rows x 3 columns]

In [423]:
Credits["cast"]

0        [{'cast_id': 14, 'character': 'Woody (voice)',...
1        [{'cast_id': 1, 'character': 'Alan Parrish', '...
2        [{'cast_id': 2, 'character': 'Max Goldman', 'c...
3        [{'cast_id': 1, 'character': "Savannah 'Vannah...
4        [{'cast_id': 1, 'character': 'George Banks', '...
                               ...                        
45471    [{'cast_id': 0, 'character': '', 'credit_id': ...
45472    [{'cast_id': 1002, 'character': 'Sister Angela...
45473    [{'cast_id': 6, 'character': 'Emily Shaw', 'cr...
45474    [{'cast_id': 2, 'character': '', 'credit_id': ...
45475                                                   []
Name: cast, Length: 45439, dtype: object

In [424]:
Credits["cast"][0]

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4t

In [425]:
#Funcion para desanidar Cast

import pandas as pd
import ast

def desanidar_cast(Credits_df):
    # Extraer y desanidar la columna 'cast'
    collection_data = Credits_df['cast'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])
    
    # Crear una lista para almacenar DataFrames individuales
    cast_list = []
    
    # Iterar sobre cada fila en el DataFrame original
    for index, row in Credits_df.iterrows():
        # Convertir la lista de diccionarios de cada fila en un DataFrame
        cast_df = pd.DataFrame(collection_data[index])
        cast_df['movie_id'] = row['id']  # Añadir el ID de la película para relacionar
        cast_list.append(cast_df)
    
    # Concatenar todos los DataFrames en uno solo
    resultado_cast = pd.concat(cast_list, ignore_index=True)
    
    return resultado_cast

resultado_cast = desanidar_cast(Credits)

# Ahora `resultado_cast` contiene los datos completamente desanidados de la columna `cast`
print(resultado_cast.head())


   cast_id                character                 credit_id  gender  \
0     14.0            Woody (voice)  52fe4284c3a36847f8024f95     2.0   
1     15.0   Buzz Lightyear (voice)  52fe4284c3a36847f8024f99     2.0   
2     16.0  Mr. Potato Head (voice)  52fe4284c3a36847f8024f9d     2.0   
3     17.0       Slinky Dog (voice)  52fe4284c3a36847f8024fa1     2.0   
4     18.0              Rex (voice)  52fe4284c3a36847f8024fa5     2.0   

        id           name  order                      profile_path  movie_id  
0     31.0      Tom Hanks    0.0  /pQFoyx7rp09CJTAb932F2g8Nlho.jpg       862  
1  12898.0      Tim Allen    1.0  /uX2xVf6pMmPepxnvFWyBtjexzgY.jpg       862  
2   7167.0    Don Rickles    2.0  /h5BcaDMPRVLHLDzbQavec4xfSdt.jpg       862  
3  12899.0     Jim Varney    3.0  /eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg       862  
4  12900.0  Wallace Shawn    4.0  /oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg       862  


In [426]:
resultado_cast

cast_id                character                 credit_id  gender  \
0          14.0            Woody (voice)  52fe4284c3a36847f8024f95     2.0   
1          15.0   Buzz Lightyear (voice)  52fe4284c3a36847f8024f99     2.0   
2          16.0  Mr. Potato Head (voice)  52fe4284c3a36847f8024f9d     2.0   
3          17.0       Slinky Dog (voice)  52fe4284c3a36847f8024fa1     2.0   
4          18.0              Rex (voice)  52fe4284c3a36847f8024fa5     2.0   
...         ...                      ...                       ...     ...   
562127      2.0                           52fe4ea59251416c7515d7d5     2.0   
562128      3.0                           52fe4ea59251416c7515d7d9     1.0   
562129      4.0                           52fe4ea59251416c7515d7dd     2.0   
562130      5.0                           52fe4ea59251416c7515d7e1     0.0   
562131      6.0                           52fe4ea59251416c7515d7e5     1.0   

               id               name  order                      profile_path  \
0            31.0          Tom Hanks    0.0  /pQFoyx7rp09CJTAb932F2g8Nlho.jpg   
1         12898.0          Tim Allen    1.0  /uX2xVf6pMmPepxnvFWyBtjexzgY.jpg   
2          7167.0        Don Rickles    2.0  /h5BcaDMPRVLHLDzbQavec4xfSdt.jpg   
3         12899.0         Jim Varney    3.0  /eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg   
4         12900.0      Wallace Shawn    4.0  /oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg   
...           ...                ...    ...                               ...   
562127   544742.0   Iwan Mosschuchin    0.0                              None   
562128  1090923.0  Nathalie Lissenko    1.0                              None   
562129  1136422.0       Pavel Pavlov    2.0                              None   
562130  1261758.0  Aleksandr Chabrov    3.0                              None   
562131    29199.0        Vera Orlova    4.0  /n1NXVGNzNxtqsMWxLT1h8GO8Kpi.jpg   

        movie_id  
0            862  
1            862  
2            862  
3            862  
4            862  
...          ...  
562127    227506  
562128    227506  
562129    227506  
562130    227506  
562131    227506  

[562132 rows x 9 columns]

In [427]:
resultado_cast.drop(columns=["cast_id", "credit_id", "order", "profile_path","gender","id","character"], inplace=True)

In [428]:
resultado_cast.sort_values(by='name', ascending=True, inplace=True)

In [429]:
resultado_cast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 562132 entries, 349934 to 491610
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   name      562132 non-null  object
 1   movie_id  562132 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 12.9+ MB


In [430]:
resultado_cast

name  movie_id
349934  \tCheung Chi-Sing     17082
48771   \tDouglas Hegdahl     56235
82076       \tRobert Osth     39867
244071         \tYip Chun     32151
266674         \tYip Chun     41387
...                   ...       ...
430943               高桥一生     40701
147091               高桥一生     15080
119988               高桥一生       393
491611                강계열    306598
491610                조병만    306598

[562132 rows x 2 columns]

In [431]:
ResultadoCastActores = resultado_cast.reset_index(drop=True)

In [432]:
ResultadoCastActores

name  movie_id
0       \tCheung Chi-Sing     17082
1       \tDouglas Hegdahl     56235
2           \tRobert Osth     39867
3              \tYip Chun     32151
4              \tYip Chun     41387
...                   ...       ...
562127               高桥一生     40701
562128               高桥一生     15080
562129               高桥一生       393
562130                강계열    306598
562131                조병만    306598

[562132 rows x 2 columns]

Al haber inconvenientes con los nombres de los actores, se debe realizar una normalización de texto.

In [433]:
# Paso 1: Eliminar caracteres de tabulación y espacios
ResultadoCastActores['name'] = ResultadoCastActores['name'].str.strip()

# Paso 2: Decodificar caracteres extraños
# Aquí se asume que los caracteres extraños son resultado de una mala codificación.
# Utilizaremos 'utf-8' como base, pero puedes ajustarlo si es necesario.
ResultadoCastActores['name'] = ResultadoCastActores['name'].str.strip()
ResultadoCastActores['name'] = ResultadoCastActores['name'].str.encode('utf-8', errors='replace').str.decode('utf-8', errors='replace')

# Paso 3: Reemplazar caracteres no deseados (si es necesario)
# También puedes usar una expresión regular para eliminar cualquier tipo de comillas
ResultadoCastActores['name'] = ResultadoCastActores['name'].str.replace(r"[\"']+", '', regex=True)
ResultadoCastActores['name'] = ResultadoCastActores['name'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)


# Mostrar el DataFrame limpio
print(ResultadoCastActores)

                   name  movie_id
0        Cheung ChiSing     17082
1       Douglas Hegdahl     56235
2           Robert Osth     39867
3              Yip Chun     32151
4              Yip Chun     41387
...                 ...       ...
562127                      40701
562128                      15080
562129                        393
562130                     306598
562131                     306598

[562132 rows x 2 columns]


Guarda de Archivos función get actores

# CSV  ResultadoCastActores  + ListaActores + FuncionActor

In [434]:
ResultadoCastActores.to_csv('datasets\\ResultadoCastActores.csv', index=False)  

In [435]:
# CHECK en CAST desanidado y listo para hacer joins con Movies
distintos_id = ResultadoCastActores["movie_id"].unique()
cantidad_id_distintos = len(distintos_id)
print("Numero de IDs de pelicula unicos:", cantidad_id_distintos)

Numero de IDs de pelicula unicos: 43018


In [436]:
# CHECK en MOVIES para corroborar tener posibles matches, parece que hay peliculas sin datos de actores
distintos_id = Movies["id"].unique()
cantidad_id_distintos = len(distintos_id)
print("Numero de IDs de pelicula unicos:", cantidad_id_distintos)

Numero de IDs de pelicula unicos: 45349


Considero que está lista la desanidación de la columna cast del archivo Credits.csv para la consulta que se necesita realizar en la función 5. Ahora voy a dejar un dataframe apropiado de Movies para hacer eficiente la consulta

In [437]:
Movies.columns

Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',
       'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'release_year', 'return'],
      dtype='object')

In [438]:
#•Se ingresa el nombre de un actor debiendo devolver su retorno, la cantidad de películas que en las que ha participado y el promedio de retorno.
#def get_actor( nombre_actor )
FuncionActor = Movies[["id","return"]]   #id para matchear con las peliculas en las que actuó, y return para medir su éxito y luego promediar en base a la cantidad de peliculas
FuncionActor.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45366 entries, 0 to 45465
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   id      45366 non-null  object 
 1   return  45366 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.0+ MB


In [439]:
FuncionActor["return"].fillna(0, inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\4129645012.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  FuncionActor["return"].fillna(0, inplace=True)
C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\4129645012.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionActor["return"].fillna(0, inplace=True)


In [440]:
for i in FuncionActor["id"]:   #No hay 1 millón de actores, por lo que el id no supera los 6 dígitos, aquí encontré outliers.
    if len(i) >6:
        print(i)

1997-08-20
2012-09-29
2014-01-01


In [441]:
FuncionActor = FuncionActor[FuncionActor["id"].str.len() <= 6]   #Elimino los outliers.

In [442]:
FuncionActor["id"] = FuncionActor["id"].astype(int)     #Cambio el tipo.

Guardo Archivos función get actor

In [443]:
FuncionActor.to_csv('datasets\\FuncionActor.csv',index=False)  

Defino una función adicional para consultas sobre el listado de actores y poder utilizar la función anterior

In [444]:
Lista_Actores = ResultadoCastActores["name"]

In [445]:
Lista_Actores.drop_duplicates(inplace=True)

In [446]:
Lista_Actores.to_csv("datasets\\ListaActores.csv", index=False)

Definir función 6 --> get director

In [447]:
#•	def get_director( nombre_director ): Se ingresa el nombre de un director que se encuentre dentro de un dataset
#  debiendo devolver el éxito del mismo medido a través del retorno. Además, deberá devolver el nombre de cada película con la fecha de lanzamiento, retorno individual, costo y ganancia de la misma.

In [448]:
Credits["crew"][0] #Check donde está el dato de director

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'A

In [449]:
#Función para desanidar crew

import pandas as pd
import ast

def desanidar_crew(Credits_df):
    # Extraer y desanidar la columna 'crew'
    collection_data = Credits_df['crew'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])
    
    # Crear una lista para almacenar DataFrames individuales
    crew_list = []
    
    # Iterar sobre cada fila en el DataFrame original
    for index, row in Credits_df.iterrows():
        # Convertir la lista de diccionarios de cada fila en un DataFrame
        crew_df = pd.DataFrame(collection_data[index])
        crew_df['movie_id'] = row['id']  # Añadir el ID de la película para relacionar
        crew_list.append(crew_df)
    
    # Concatenar todos los DataFrames en uno solo
    resultado_crew = pd.concat(crew_list, ignore_index=True)
    
    return resultado_crew

resultado_crew = desanidar_crew(Credits)

print(resultado_crew.head())

# Función similar a la que desanidó Cast

                  credit_id department  gender       id         job  \
0  52fe4284c3a36847f8024f49  Directing     2.0   7879.0    Director   
1  52fe4284c3a36847f8024f4f    Writing     2.0  12891.0  Screenplay   
2  52fe4284c3a36847f8024f55    Writing     2.0      7.0  Screenplay   
3  52fe4284c3a36847f8024f5b    Writing     2.0  12892.0  Screenplay   
4  52fe4284c3a36847f8024f61    Writing     0.0  12893.0  Screenplay   

             name                      profile_path  movie_id  
0   John Lasseter  /7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg       862  
1     Joss Whedon  /dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg       862  
2  Andrew Stanton  /pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg       862  
3      Joel Cohen  /dAubAiZcvKFbboWlj7oXOkZnTSu.jpg       862  
4    Alec Sokolow  /v79vlRYi94BZUQnkkyznbGUZLjT.jpg       862  


In [450]:
resultado_crew.head()

credit_id department  gender       id         job  \
0  52fe4284c3a36847f8024f49  Directing     2.0   7879.0    Director   
1  52fe4284c3a36847f8024f4f    Writing     2.0  12891.0  Screenplay   
2  52fe4284c3a36847f8024f55    Writing     2.0      7.0  Screenplay   
3  52fe4284c3a36847f8024f5b    Writing     2.0  12892.0  Screenplay   
4  52fe4284c3a36847f8024f61    Writing     0.0  12893.0  Screenplay   

             name                      profile_path  movie_id  
0   John Lasseter  /7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg       862  
1     Joss Whedon  /dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg       862  
2  Andrew Stanton  /pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg       862  
3      Joel Cohen  /dAubAiZcvKFbboWlj7oXOkZnTSu.jpg       862  
4    Alec Sokolow  /v79vlRYi94BZUQnkkyznbGUZLjT.jpg       862

In [451]:
resultado_crew[resultado_crew["job"] == "Director"]["department"].value_counts()

department
Directing    49008
Name: count, dtype: int64

In [452]:
resultado_crew.drop(columns=["credit_id", "gender", "id","profile_path","department"], inplace=True)

In [453]:
resultado_crew.head()

job            name  movie_id
0    Director   John Lasseter       862
1  Screenplay     Joss Whedon       862
2  Screenplay  Andrew Stanton       862
3  Screenplay      Joel Cohen       862
4  Screenplay    Alec Sokolow       862

In [454]:
resultado_crew = resultado_crew.where(resultado_crew["job"]=='Director')    # Selecciono como datos relevantes, aquellos en que la columna job sean iguales a Director

In [455]:
resultado_crew

job              name  movie_id
0       Director     John Lasseter     862.0
1            NaN               NaN       NaN
2            NaN               NaN       NaN
3            NaN               NaN       NaN
4            NaN               NaN       NaN
...          ...               ...       ...
463922       NaN               NaN       NaN
463923       NaN               NaN       NaN
463924  Director  Yakov Protazanov  227506.0
463925       NaN               NaN       NaN
463926  Director     Daisy Asquith  461257.0

[463927 rows x 3 columns]

In [456]:
resultado_crew.dropna(inplace=True)

In [457]:
resultado_crew

job              name  movie_id
0       Director     John Lasseter     862.0
109     Director      Joe Johnston    8844.0
122     Director     Howard Deutch   15602.0
126     Director   Forest Whitaker   31357.0
141     Director     Charles Shyer   11862.0
...          ...               ...       ...
463904  Director  Hamid Nematollah  439050.0
463913  Director          Lav Diaz  111109.0
463919  Director    Mark L. Lester   67758.0
463924  Director  Yakov Protazanov  227506.0
463926  Director     Daisy Asquith  461257.0

[49008 rows x 3 columns]

Corroboración simple y arbitraria.

In [458]:
print(resultado_crew[resultado_crew["name"]== "Quentin Tarantino"])

             job               name  movie_id
403     Director  Quentin Tarantino       5.0
4957    Director  Quentin Tarantino     680.0
16539   Director  Quentin Tarantino     500.0
26793   Director  Quentin Tarantino     184.0
103019  Director  Quentin Tarantino      24.0
112713  Director  Quentin Tarantino     393.0
172624  Director  Quentin Tarantino    1991.0
194845  Director  Quentin Tarantino   16869.0
260884  Director  Quentin Tarantino   68718.0
334724  Director  Quentin Tarantino  273248.0
431108  Director  Quentin Tarantino   10614.0


In [459]:
resultado_crew["movie_id"] = resultado_crew["movie_id"].astype(int)

In [460]:
resultado_crew.head()

job             name  movie_id
0    Director    John Lasseter       862
109  Director     Joe Johnston      8844
122  Director    Howard Deutch     15602
126  Director  Forest Whitaker     31357
141  Director    Charles Shyer     11862

CORREGIR FUNCION

In [461]:
# Al igual que con los actores, se debe normalizar el nombre de los directores, se encontraban caracteres extraños.

# Paso 1: Eliminar caracteres de tabulación y espacios
#resultado_crew['name'] = resultado_crew['name'].str.strip()

# Paso 2: Decodificar caracteres extraños
# Aquí se asume que los caracteres extraños son resultado de una mala codificación.
# Utilizaremos 'utf-8' como base, pero puedes ajustarlo si es necesario.
#resultado_crew['name'] = resultado_cast['name'].str.strip()
#resultado_crew['name'] = resultado_crew['name'].str.encode('utf-8', errors='replace').str.decode('utf-8', errors='replace')

# Paso 3: Reemplazar caracteres no deseados (si es necesario)
# También puedes usar una expresión regular para eliminar cualquier tipo de comillas
#resultado_crew['name'] = resultado_crew['name'].str.replace(r"[\"']+", '', regex=True)
resultado_crew['name'] = resultado_crew['name'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)


# Mostrar el DataFrame limpio
print(resultado_crew)

             job              name  movie_id
0       Director     John Lasseter       862
109     Director      Joe Johnston      8844
122     Director     Howard Deutch     15602
126     Director   Forest Whitaker     31357
141     Director     Charles Shyer     11862
...          ...               ...       ...
463904  Director  Hamid Nematollah    439050
463913  Director          Lav Diaz    111109
463919  Director     Mark L Lester     67758
463924  Director  Yakov Protazanov    227506
463926  Director     Daisy Asquith    461257

[49008 rows x 3 columns]


In [462]:
resultado_crew["job"].value_counts()

job
Director    49008
Name: count, dtype: int64

In [463]:
resultado_crew = resultado_crew.drop(columns=["job"])

Guardar Archivos Función get director

# CSV ResultadoCrew

In [464]:
resultado_crew.to_csv('datasets\\ResultadoCrew.csv',index=False)  

In [465]:
#  debiendo devolver el éxito del mismo medido a través del retorno. Además, deberá devolver el nombre de cada película con la fecha de lanzamiento, retorno individual, costo y ganancia de la misma.
FuncionDirector = Movies[["id","title","release_date","return","budget","revenue"]]

In [466]:
FuncionDirector

id                        title release_date     return    budget  \
0         862                    Toy Story   1995-10-30  12.451801  30000000   
1        8844                      Jumanji   1995-12-15   4.043035  65000000   
2       15602             Grumpier Old Men   1995-12-22   0.000000         0   
3       31357            Waiting to Exhale   1995-12-22   5.090760  16000000   
4       11862  Father of the Bride Part II   1995-02-10   0.000000         0   
...       ...                          ...          ...        ...       ...   
45460   30840                   Robin Hood   1991-05-13   0.000000         0   
45462  111109          Century of Birthing   2011-11-17   0.000000         0   
45463   67758                     Betrayal   2003-08-01   0.000000         0   
45464  227506             Satan Triumphant   1917-10-21   0.000000         0   
45465  461257                     Queerama   2017-06-09   0.000000         0   

           revenue  
0      373554033.0  
1      262797249.0  
2              0.0  
3       81452156.0  
4       76578911.0  
...            ...  
45460          0.0  
45462          0.0  
45463          0.0  
45464          0.0  
45465          0.0  

[45366 rows x 6 columns]

In [467]:
FuncionDirector.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45366 entries, 0 to 45465
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   id            45366 non-null  object        
 1   title         45363 non-null  object        
 2   release_date  45363 non-null  datetime64[ns]
 3   return        45366 non-null  float64       
 4   budget        45366 non-null  int32         
 5   revenue       45366 non-null  float64       
dtypes: datetime64[ns](1), float64(2), int32(1), object(2)
memory usage: 3.3+ MB


In [468]:
FuncionDirector["return"] = FuncionDirector["return"].fillna(0)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1754726078.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionDirector["return"] = FuncionDirector["return"].fillna(0)


In [469]:
for i in FuncionDirector["id"]:
    if len(i) >6:
        print(i)
FuncionDirector = FuncionDirector[FuncionDirector["id"].str.len() <= 6]     # No considerar los id mayores a 6 dígitos.

1997-08-20
2012-09-29
2014-01-01


In [470]:
FuncionDirector["id"] = FuncionDirector["id"].astype(int)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3238847082.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionDirector["id"] = FuncionDirector["id"].astype(int)


In [471]:
FuncionDirector

id                        title release_date     return    budget  \
0         862                    Toy Story   1995-10-30  12.451801  30000000   
1        8844                      Jumanji   1995-12-15   4.043035  65000000   
2       15602             Grumpier Old Men   1995-12-22   0.000000         0   
3       31357            Waiting to Exhale   1995-12-22   5.090760  16000000   
4       11862  Father of the Bride Part II   1995-02-10   0.000000         0   
...       ...                          ...          ...        ...       ...   
45460   30840                   Robin Hood   1991-05-13   0.000000         0   
45462  111109          Century of Birthing   2011-11-17   0.000000         0   
45463   67758                     Betrayal   2003-08-01   0.000000         0   
45464  227506             Satan Triumphant   1917-10-21   0.000000         0   
45465  461257                     Queerama   2017-06-09   0.000000         0   

           revenue  
0      373554033.0  
1      262797249.0  
2              0.0  
3       81452156.0  
4       76578911.0  
...            ...  
45460          0.0  
45462          0.0  
45463          0.0  
45464          0.0  
45465          0.0  

[45363 rows x 6 columns]

In [472]:
FuncionDirector.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45363 entries, 0 to 45465
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   id            45363 non-null  int32         
 1   title         45363 non-null  object        
 2   release_date  45363 non-null  datetime64[ns]
 3   return        45363 non-null  float64       
 4   budget        45363 non-null  int32         
 5   revenue       45363 non-null  float64       
dtypes: datetime64[ns](1), float64(2), int32(2), object(1)
memory usage: 2.1+ MB


In [473]:
FuncionDirector["return"]

0        12.451801
1         4.043035
2         0.000000
3         5.090760
4         0.000000
           ...    
45460     0.000000
45462     0.000000
45463     0.000000
45464     0.000000
45465     0.000000
Name: return, Length: 45363, dtype: float64

In [474]:
FuncionDirector["return"] = FuncionDirector["return"]*100           # Aplicar porcentaje al calculo del retorno.

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3350807559.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FuncionDirector["return"] = FuncionDirector["return"]*100           # Aplicar porcentaje al calculo del retorno.


In [475]:
FuncionDirector.info() #Dataset listo para dar la función.

<class 'pandas.core.frame.DataFrame'>
Index: 45363 entries, 0 to 45465
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   id            45363 non-null  int32         
 1   title         45363 non-null  object        
 2   release_date  45363 non-null  datetime64[ns]
 3   return        45363 non-null  float64       
 4   budget        45363 non-null  int32         
 5   revenue       45363 non-null  float64       
dtypes: datetime64[ns](1), float64(2), int32(2), object(1)
memory usage: 2.1+ MB


Guardar Archivos función get director

# CSV FuncionDirector

In [476]:
FuncionDirector.to_csv('datasets\\FuncionDirector.csv', index=False)

# PREPARACION Y DESARROLLO FUNCION RECOMENDACION

Función Seleccionada

In [477]:
MachineLearning = Movies[["id","title","belongs_to_collection","vote_average","overview","production_companies"]]   #Defino columnas relevantes

In [478]:
MachineLearning['overview'] = MachineLearning['overview'].fillna('')

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\127337352.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MachineLearning['overview'] = MachineLearning['overview'].fillna('')


## PREPROCESAMIENTO PARA PLN

In [479]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')


# Función para eliminar signos de puntuación
def remove_punctuation(text):
    return re.sub(r'[^\w\s]', '', text)

# Función para eliminar números
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Función para convertir a minúsculas
def to_lowercase(text):
    return text.lower()

# Función para eliminar stop words
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    return ' '.join(word for word in text.split() if word not in stop_words)

# Función para eliminar espacios en blanco
def remove_whitespace(text):
    return re.sub(r'\s+', ' ', text).strip()

# Función para aplicar stemming
def stemming(text):
    stemmer = PorterStemmer()
    return ' '.join(stemmer.stem(word) for word in text.split())

# Función para aplicar lemmatization                    #NO UTILIZADA
def lemmatization(text):
    lemmatizer = WordNetLemmatizer()
    return ' '.join(lemmatizer.lemmatize(word) for word in text.split())

# Preprocesamiento
def preprocess_text(text):
    text = remove_punctuation(text)
    text = remove_numbers(text)
    text = to_lowercase(text)
    text = remove_stopwords(text)
    text = remove_whitespace(text)
    # Elegir entre stemming o lemmatization
    text = stemming(text)  # O lemmatization(text)
    return text

MachineLearning['preprocessed_overview'] = MachineLearning['overview'].apply(preprocess_text)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Aleja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Aleja\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3150377302.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MachineLearning['preprocessed_overview'] = MachineLearning['overview'].apply(preprocess_text)


In [480]:
MachineLearning     # La salida con el preprocesamiento incluido.

id                        title           belongs_to_collection  \
0         862                    Toy Story            Toy Story Collection   
1        8844                      Jumanji                             NaN   
2       15602             Grumpier Old Men       Grumpy Old Men Collection   
3       31357            Waiting to Exhale                             NaN   
4       11862  Father of the Bride Part II  Father of the Bride Collection   
...       ...                          ...                             ...   
45460   30840                   Robin Hood                             NaN   
45462  111109          Century of Birthing                             NaN   
45463   67758                     Betrayal                             NaN   
45464  227506             Satan Triumphant                             NaN   
45465  461257                     Queerama                             NaN   

       vote_average                                           overview  \
0               7.7  Led by Woody, Andy's toys live happily in his ...   
1               6.9  When siblings Judy and Peter discover an encha...   
2               6.5  A family wedding reignites the ancient feud be...   
3               6.1  Cheated on, mistreated and stepped on, the wom...   
4               5.7  Just when George Banks has recovered from his ...   
...             ...                                                ...   
45460           5.7  Yet another version of the classic epic, with ...   
45462           9.0  An artist struggles to finish his work while a...   
45463           3.8  When one of her hits goes wrong, a professiona...   
45464           0.0  In a small town live two brothers, one a minis...   
45465           0.0  50 years after decriminalisation of homosexual...   

                                    production_companies  \
0                                Pixar Animation Studios   
1      TriStar Pictures and Teitler Film and Intersco...   
2                        Warner Bros. and Lancaster Gate   
3                 Twentieth Century Fox Film Corporation   
4          Sandollar Productions and Touchstone Pictures   
...                                                  ...   
45460                                                NaN   
45462                                                NaN   
45463                                                NaN   
45464                                                NaN   
45465                                                NaN   

                                   preprocessed_overview  
0      led woodi andi toy live happili room andi birt...  
1      sibl judi peter discov enchant board game open...  
2      famili wed reignit ancient feud nextdoor neigh...  
3      cheat mistreat step women hold breath wait elu...  
4      georg bank recov daughter wed receiv news she ...  
...                                                  ...  
45460  yet anoth version classic epic enough variat m...  
45462  artist struggl finish work storylin cult play ...  
45463  one hit goe wrong profession assassin end suit...  
45464  small town live two brother one minist one hun...  
45465  year decriminalis homosexu uk director daisi a...  

[45366 rows x 7 columns]

In [481]:
MachineLearning.rename(columns={"preprocessed_overview": "PreProcesamientoStemming"}, inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\1163928806.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MachineLearning.rename(columns={"preprocessed_overview": "PreProcesamientoStemming"}, inplace=True)


In [482]:
MachineLearning

id                        title           belongs_to_collection  \
0         862                    Toy Story            Toy Story Collection   
1        8844                      Jumanji                             NaN   
2       15602             Grumpier Old Men       Grumpy Old Men Collection   
3       31357            Waiting to Exhale                             NaN   
4       11862  Father of the Bride Part II  Father of the Bride Collection   
...       ...                          ...                             ...   
45460   30840                   Robin Hood                             NaN   
45462  111109          Century of Birthing                             NaN   
45463   67758                     Betrayal                             NaN   
45464  227506             Satan Triumphant                             NaN   
45465  461257                     Queerama                             NaN   

       vote_average                                           overview  \
0               7.7  Led by Woody, Andy's toys live happily in his ...   
1               6.9  When siblings Judy and Peter discover an encha...   
2               6.5  A family wedding reignites the ancient feud be...   
3               6.1  Cheated on, mistreated and stepped on, the wom...   
4               5.7  Just when George Banks has recovered from his ...   
...             ...                                                ...   
45460           5.7  Yet another version of the classic epic, with ...   
45462           9.0  An artist struggles to finish his work while a...   
45463           3.8  When one of her hits goes wrong, a professiona...   
45464           0.0  In a small town live two brothers, one a minis...   
45465           0.0  50 years after decriminalisation of homosexual...   

                                    production_companies  \
0                                Pixar Animation Studios   
1      TriStar Pictures and Teitler Film and Intersco...   
2                        Warner Bros. and Lancaster Gate   
3                 Twentieth Century Fox Film Corporation   
4          Sandollar Productions and Touchstone Pictures   
...                                                  ...   
45460                                                NaN   
45462                                                NaN   
45463                                                NaN   
45464                                                NaN   
45465                                                NaN   

                                PreProcesamientoStemming  
0      led woodi andi toy live happili room andi birt...  
1      sibl judi peter discov enchant board game open...  
2      famili wed reignit ancient feud nextdoor neigh...  
3      cheat mistreat step women hold breath wait elu...  
4      georg bank recov daughter wed receiv news she ...  
...                                                  ...  
45460  yet anoth version classic epic enough variat m...  
45462  artist struggl finish work storylin cult play ...  
45463  one hit goe wrong profession assassin end suit...  
45464  small town live two brother one minist one hun...  
45465  year decriminalis homosexu uk director daisi a...  

[45366 rows x 7 columns]

In [483]:
MachineLearning.to_csv("datasets\\MachineLearning.csv",index=False)       # Esto fue para tener un punto de partida avanzado en caso de cometer alguna mala transformación posterior.

In [484]:
MachineLearning = pd.read_csv("datasets\\MachineLearning.csv")


In [485]:
# Filtrado de columnas. Eliminar redundancias.

MLStemming = MachineLearning[["id","title","belongs_to_collection","vote_average","production_companies","PreProcesamientoStemming"]]

In [486]:
MLStemming

id                        title           belongs_to_collection  \
0         862                    Toy Story            Toy Story Collection   
1        8844                      Jumanji                             NaN   
2       15602             Grumpier Old Men       Grumpy Old Men Collection   
3       31357            Waiting to Exhale                             NaN   
4       11862  Father of the Bride Part II  Father of the Bride Collection   
...       ...                          ...                             ...   
45361   30840                   Robin Hood                             NaN   
45362  111109          Century of Birthing                             NaN   
45363   67758                     Betrayal                             NaN   
45364  227506             Satan Triumphant                             NaN   
45365  461257                     Queerama                             NaN   

       vote_average                               production_companies  \
0               7.7                            Pixar Animation Studios   
1               6.9  TriStar Pictures and Teitler Film and Intersco...   
2               6.5                    Warner Bros. and Lancaster Gate   
3               6.1             Twentieth Century Fox Film Corporation   
4               5.7      Sandollar Productions and Touchstone Pictures   
...             ...                                                ...   
45361           5.7                                                NaN   
45362           9.0                                                NaN   
45363           3.8                                                NaN   
45364           0.0                                                NaN   
45365           0.0                                                NaN   

                                PreProcesamientoStemming  
0      led woodi andi toy live happili room andi birt...  
1      sibl judi peter discov enchant board game open...  
2      famili wed reignit ancient feud nextdoor neigh...  
3      cheat mistreat step women hold breath wait elu...  
4      georg bank recov daughter wed receiv news she ...  
...                                                  ...  
45361  yet anoth version classic epic enough variat m...  
45362  artist struggl finish work storylin cult play ...  
45363  one hit goe wrong profession assassin end suit...  
45364  small town live two brother one minist one hun...  
45365  year decriminalis homosexu uk director daisi a...  

[45366 rows x 6 columns]

In [487]:
MLStemming.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45366 entries, 0 to 45365
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   id                        45366 non-null  object 
 1   title                     45363 non-null  object 
 2   belongs_to_collection     4479 non-null   object 
 3   vote_average              45363 non-null  float64
 4   production_companies      33511 non-null  object 
 5   PreProcesamientoStemming  44419 non-null  object 
dtypes: float64(1), object(5)
memory usage: 2.1+ MB


Tarda entre 6 y 9 minutos para ejecutarse , una vez tardó 18. Procesador Intel i7 7ma gen con 32 gb ddr4.

In [488]:
import pandas as pd
import spacy

# Cargar modelo Spacy, asegurar lenguaje acorde.
nlp = spacy.load('en_core_web_sm')

# Definir la función de tokenización.
def tokenizar_texto(texto):
    if isinstance(texto, str):  # Corroborar que la entrada sea un str.
        doc = nlp(texto)
        return [token.text for token in doc]
    else:
        return []  # Devuelve una lista vacia en caso de que no sea str.

# Aplicar a la columna preprocesada.
MLStemming['tokens'] = MLStemming['PreProcesamientoStemming'].apply(tokenizar_texto)

print(MLStemming[['id', 'title', 'tokens']].head())

      id                        title  \
0    862                    Toy Story   
1   8844                      Jumanji   
2  15602             Grumpier Old Men   
3  31357            Waiting to Exhale   
4  11862  Father of the Bride Part II   

                                              tokens  
0  [led, woodi, andi, toy, live, happili, room, a...  
1  [sibl, judi, peter, discov, enchant, board, ga...  
2  [famili, we, d, reignit, ancient, feud, nextdo...  
3  [cheat, mistreat, step, women, hold, breath, w...  
4  [georg, bank, recov, daughter, we, d, receiv, ...  


In [489]:
MLStemmingTokenizado = MLStemming

In [490]:
MLStemmingTokenizado.to_csv("datasets\\MLStemmingTokenizado.csv",index=False)     # Misma lógica que el anterior guardado.

In [492]:
data = pd.read_csv("datasets\\MLStemmingTokenizado.csv")

In [493]:
data

id                        title           belongs_to_collection  \
0         862                    Toy Story            Toy Story Collection   
1        8844                      Jumanji                             NaN   
2       15602             Grumpier Old Men       Grumpy Old Men Collection   
3       31357            Waiting to Exhale                             NaN   
4       11862  Father of the Bride Part II  Father of the Bride Collection   
...       ...                          ...                             ...   
45361   30840                   Robin Hood                             NaN   
45362  111109          Century of Birthing                             NaN   
45363   67758                     Betrayal                             NaN   
45364  227506             Satan Triumphant                             NaN   
45365  461257                     Queerama                             NaN   

       vote_average                               production_companies  \
0               7.7                            Pixar Animation Studios   
1               6.9  TriStar Pictures and Teitler Film and Intersco...   
2               6.5                    Warner Bros. and Lancaster Gate   
3               6.1             Twentieth Century Fox Film Corporation   
4               5.7      Sandollar Productions and Touchstone Pictures   
...             ...                                                ...   
45361           5.7                                                NaN   
45362           9.0                                                NaN   
45363           3.8                                                NaN   
45364           0.0                                                NaN   
45365           0.0                                                NaN   

                                PreProcesamientoStemming  \
0      led woodi andi toy live happili room andi birt...   
1      sibl judi peter discov enchant board game open...   
2      famili wed reignit ancient feud nextdoor neigh...   
3      cheat mistreat step women hold breath wait elu...   
4      georg bank recov daughter wed receiv news she ...   
...                                                  ...   
45361  yet anoth version classic epic enough variat m...   
45362  artist struggl finish work storylin cult play ...   
45363  one hit goe wrong profession assassin end suit...   
45364  small town live two brother one minist one hun...   
45365  year decriminalis homosexu uk director daisi a...   

                                                  tokens  
0      ['led', 'woodi', 'andi', 'toy', 'live', 'happi...  
1      ['sibl', 'judi', 'peter', 'discov', 'enchant',...  
2      ['famili', 'we', 'd', 'reignit', 'ancient', 'f...  
3      ['cheat', 'mistreat', 'step', 'women', 'hold',...  
4      ['georg', 'bank', 'recov', 'daughter', 'we', '...  
...                                                  ...  
45361  ['yet', 'anoth', 'version', 'classic', 'epic',...  
45362  ['artist', 'struggl', 'finish', 'work', 'story...  
45363  ['one', 'hit', 'goe', 'wrong', 'profession', '...  
45364  ['small', 'town', 'live', 'two', 'brother', 'o...  
45365  ['year', 'decriminalis', 'homosexu', 'uk', 'di...  

[45366 rows x 7 columns]

In [494]:
data.columns

Index(['id', 'title', 'belongs_to_collection', 'vote_average',
       'production_companies', 'PreProcesamientoStemming', 'tokens'],
      dtype='object')

In [495]:
data = data[["id","title","vote_average","tokens"]]         # Dataframe bien refinado para la función. Aún falta pulir.

In [496]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45366 entries, 0 to 45365
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            45366 non-null  object 
 1   title         45363 non-null  object 
 2   vote_average  45363 non-null  float64
 3   tokens        45366 non-null  object 
dtypes: float64(1), object(3)
memory usage: 1.4+ MB


In [497]:
data

id                        title  vote_average  \
0         862                    Toy Story           7.7   
1        8844                      Jumanji           6.9   
2       15602             Grumpier Old Men           6.5   
3       31357            Waiting to Exhale           6.1   
4       11862  Father of the Bride Part II           5.7   
...       ...                          ...           ...   
45361   30840                   Robin Hood           5.7   
45362  111109          Century of Birthing           9.0   
45363   67758                     Betrayal           3.8   
45364  227506             Satan Triumphant           0.0   
45365  461257                     Queerama           0.0   

                                                  tokens  
0      ['led', 'woodi', 'andi', 'toy', 'live', 'happi...  
1      ['sibl', 'judi', 'peter', 'discov', 'enchant',...  
2      ['famili', 'we', 'd', 'reignit', 'ancient', 'f...  
3      ['cheat', 'mistreat', 'step', 'women', 'hold',...  
4      ['georg', 'bank', 'recov', 'daughter', 'we', '...  
...                                                  ...  
45361  ['yet', 'anoth', 'version', 'classic', 'epic',...  
45362  ['artist', 'struggl', 'finish', 'work', 'story...  
45363  ['one', 'hit', 'goe', 'wrong', 'profession', '...  
45364  ['small', 'town', 'live', 'two', 'brother', 'o...  
45365  ['year', 'decriminalis', 'homosexu', 'uk', 'di...  

[45366 rows x 4 columns]

In [498]:
total_palabras = data['tokens'].apply(len).sum()
print(f'Total de palabras en la columna tokens: {total_palabras}')          # Es muy extenso para desarrollar matrices TF - IDF.

Total de palabras en la columna tokens: 13095185


TOTAL DE PALABRAS EN COLUMNA TOKENS 13,095,185

In [501]:
data

id                        title  vote_average  \
0         862                    Toy Story           7.7   
1        8844                      Jumanji           6.9   
2       15602             Grumpier Old Men           6.5   
3       31357            Waiting to Exhale           6.1   
4       11862  Father of the Bride Part II           5.7   
...       ...                          ...           ...   
45361   30840                   Robin Hood           5.7   
45362  111109          Century of Birthing           9.0   
45363   67758                     Betrayal           3.8   
45364  227506             Satan Triumphant           0.0   
45365  461257                     Queerama           0.0   

                                                  tokens  
0      ['led', 'woodi', 'andi', 'toy', 'live', 'happi...  
1      ['sibl', 'judi', 'peter', 'discov', 'enchant',...  
2      ['famili', 'we', 'd', 'reignit', 'ancient', 'f...  
3      ['cheat', 'mistreat', 'step', 'women', 'hold',...  
4      ['georg', 'bank', 'recov', 'daughter', 'we', '...  
...                                                  ...  
45361  ['yet', 'anoth', 'version', 'classic', 'epic',...  
45362  ['artist', 'struggl', 'finish', 'work', 'story...  
45363  ['one', 'hit', 'goe', 'wrong', 'profession', '...  
45364  ['small', 'town', 'live', 'two', 'brother', 'o...  
45365  ['year', 'decriminalis', 'homosexu', 'uk', 'di...  

[45366 rows x 4 columns]

In [502]:
import pandas as pd
from collections import Counter
from nltk.corpus import stopwords
import ast
import nltk

nltk.download('stopwords')

# Convierte 'tokens' a listas si es necesario. Ha sido un dolor de cabeza.
data['tokens'] = data['tokens'].apply(ast.literal_eval)

# Definir función para filtrar tokens por relevancia. En este caso los hiperparametros son 100 más comunes y 100 máximo por fila.
def filter_relevant_tokens(tokens):
    stop_words = set(stopwords.words('english'))
    filtered = [token for token in tokens if token not in stop_words and len(token) > 3]
    token_counts = Counter(filtered)
    most_common_in_row = [word for word, _ in token_counts.most_common(100)]
    return most_common_in_row[:100]

# Aplicamos la función de filtrado a la columna 'tokens'
data['filtered_tokens'] = data['tokens'].apply(filter_relevant_tokens)

result_data = data[['id', 'title', 'vote_average', 'filtered_tokens']]

print(result_data.head())


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Aleja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3546602040.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tokens'] = data['tokens'].apply(ast.literal_eval)


      id                        title  vote_average  \
0    862                    Toy Story           7.7   
1   8844                      Jumanji           6.9   
2  15602             Grumpier Old Men           6.5   
3  31357            Waiting to Exhale           6.1   
4  11862  Father of the Bride Part II           5.7   

                                     filtered_tokens  
0  [woodi, andi, buzz, live, happili, room, birth...  
1  [game, alan, sibl, judi, peter, discov, enchan...  
2  [fish, local, famili, reignit, ancient, feud, ...  
3  [breath, cheat, mistreat, step, women, hold, w...  
4  [georg, plan, bank, recov, daughter, receiv, n...  


C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3546602040.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['filtered_tokens'] = data['tokens'].apply(filter_relevant_tokens)


In [503]:
total_palabras = data['filtered_tokens'].apply(len).sum()
print(f'Total de palabras en la columna tokens: {total_palabras}')          # La reducción de palabras es sustancial +90%.

Total de palabras en la columna tokens: 1130898


Total de palabras luego del filtrado = 1,130,898

In [504]:
data        # Listo para ser ingresado. 

id                        title  vote_average  \
0         862                    Toy Story           7.7   
1        8844                      Jumanji           6.9   
2       15602             Grumpier Old Men           6.5   
3       31357            Waiting to Exhale           6.1   
4       11862  Father of the Bride Part II           5.7   
...       ...                          ...           ...   
45361   30840                   Robin Hood           5.7   
45362  111109          Century of Birthing           9.0   
45363   67758                     Betrayal           3.8   
45364  227506             Satan Triumphant           0.0   
45365  461257                     Queerama           0.0   

                                                  tokens  \
0      [led, woodi, andi, toy, live, happili, room, a...   
1      [sibl, judi, peter, discov, enchant, board, ga...   
2      [famili, we, d, reignit, ancient, feud, nextdo...   
3      [cheat, mistreat, step, women, hold, breath, w...   
4      [georg, bank, recov, daughter, we, d, receiv, ...   
...                                                  ...   
45361  [yet, anoth, version, classic, epic, enough, v...   
45362  [artist, struggl, finish, work, storylin, cult...   
45363  [one, hit, goe, wrong, profession, assassin, e...   
45364  [small, town, live, two, brother, one, minist,...   
45365  [year, decriminalis, homosexu, uk, director, d...   

                                         filtered_tokens  
0      [woodi, andi, buzz, live, happili, room, birth...  
1      [game, alan, sibl, judi, peter, discov, enchan...  
2      [fish, local, famili, reignit, ancient, feud, ...  
3      [breath, cheat, mistreat, step, women, hold, w...  
4      [georg, plan, bank, recov, daughter, receiv, n...  
...                                                  ...  
45361  [stori, anoth, version, classic, epic, enough,...  
45362  [artist, struggl, finish, work, storylin, cult...  
45363  [wrong, profession, assassin, suitcas, full, m...  
45364  [minist, stranger, live, brother, chapel, smal...  
45365  [year, decriminalis, homosexu, director, daisi...  

[45366 rows x 5 columns]

In [505]:
data.rename(columns={"filtered_tokens": "TokensLista"}, inplace=True)

C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\785919287.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns={"filtered_tokens": "TokensLista"}, inplace=True)


Guarda del Archivo data_reduction CSV

In [506]:
data.to_csv("datasets\\DataReduction.csv",index=False)

In [507]:
data

id                        title  vote_average  \
0         862                    Toy Story           7.7   
1        8844                      Jumanji           6.9   
2       15602             Grumpier Old Men           6.5   
3       31357            Waiting to Exhale           6.1   
4       11862  Father of the Bride Part II           5.7   
...       ...                          ...           ...   
45361   30840                   Robin Hood           5.7   
45362  111109          Century of Birthing           9.0   
45363   67758                     Betrayal           3.8   
45364  227506             Satan Triumphant           0.0   
45365  461257                     Queerama           0.0   

                                                  tokens  \
0      [led, woodi, andi, toy, live, happili, room, a...   
1      [sibl, judi, peter, discov, enchant, board, ga...   
2      [famili, we, d, reignit, ancient, feud, nextdo...   
3      [cheat, mistreat, step, women, hold, breath, w...   
4      [georg, bank, recov, daughter, we, d, receiv, ...   
...                                                  ...   
45361  [yet, anoth, version, classic, epic, enough, v...   
45362  [artist, struggl, finish, work, storylin, cult...   
45363  [one, hit, goe, wrong, profession, assassin, e...   
45364  [small, town, live, two, brother, one, minist,...   
45365  [year, decriminalis, homosexu, uk, director, d...   

                                             TokensLista  
0      [woodi, andi, buzz, live, happili, room, birth...  
1      [game, alan, sibl, judi, peter, discov, enchan...  
2      [fish, local, famili, reignit, ancient, feud, ...  
3      [breath, cheat, mistreat, step, women, hold, w...  
4      [georg, plan, bank, recov, daughter, receiv, n...  
...                                                  ...  
45361  [stori, anoth, version, classic, epic, enough,...  
45362  [artist, struggl, finish, work, storylin, cult...  
45363  [wrong, profession, assassin, suitcas, full, m...  
45364  [minist, stranger, live, brother, chapel, smal...  
45365  [year, decriminalis, homosexu, director, daisi...  

[45366 rows x 5 columns]

In [508]:
type(data["TokensLista"][0])

list

In [509]:
data = pd.read_csv("datasets\\DataReduction.csv")

Último ajuste previo a la función, el tipo de dato a trabajar es fundamental. Por eso el dolor de cabeza.

In [510]:
#Verifica el tipo de dato en 'TokensLista'
print(data['TokensLista'].dtype)

# Si 'TokensLista' contiene cadenas que representan listas, conviértelo a listas
data['TokensLista'] = data['TokensLista'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Ahora verifica que los elementos son listas
print(data['TokensLista'].apply(type).value_counts())

# Ahora podemos continuar con tu función
data['TokensTexto'] = data['TokensLista'].apply(lambda x: ' '.join(x))

object
TokensLista
<class 'list'>    45366
Name: count, dtype: int64


In [511]:
titulo_ingresado="Toy Story"

Definimos la Función de Recomendación

In [512]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Aplicar TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(data['TokensTexto'])

# Obtener el índice de la película ingresada
idx = data[data['title'] == titulo_ingresado].index[0]

# Calcular la similitud
cosine_similarities = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()

# Obtener las recomendaciones
recommendations_indices = cosine_similarities.argsort()[-6:-1][::-1]  # 5 recomendaciones

# Combina con el voto promedio
recommendations = data.iloc[recommendations_indices]
recommendations['similarity'] = cosine_similarities[recommendations_indices]
recommendations = recommendations.sort_values(by='vote_average', ascending=False)

print(recommendations[['title', 'vote_average', 'similarity']])

                        title  vote_average  similarity
15337             Toy Story 3           7.6    0.267745
2994              Toy Story 2           7.3    0.338044
1252         My Life as a Dog           7.3    0.149189
1945   The Incredible Journey           6.3    0.165916
10932                The Wild           5.1    0.180675


C:\Users\Aleja\AppData\Local\Temp\ipykernel_8204\3961621390.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendations['similarity'] = cosine_similarities[recommendations_indices]


Podría indicarle a la función que si recomienda una película con el mismo nombre, no lo haga dos veces. También limitar la impresión de similaridad. La considero apta como MVP.

# Conteo de pruebas realizadas.

1er prueba de ejecución de código completo satisfactoria ---> 23 minutos 26 segundos

2da prueba de ejecución de código completo satisfactoria ---> 19 minutos 30 segundos

3ra prueba, código modificado ---> 12 Minutos

4ta prueba, código modificado ---> 16-17 Minutos